### ISSUE TITLE
Add the iron-swords topic to your repo

### ISSUE THREAD

**Issue by ohadschn** [LeggoMahEggo/miklat-finder-open-source#1]
Hello fellow developers!
May I suggest you associate your repo with the `iron-swords` topic?
We did this with our project (https://github.com/4tals/LinksForIsrael), and the more projects join, the more discoverable such great projects would be: https://github.com/topics/iron-swords

**Comment by LeggoMahEggo** [comment]
I have done so, thank you for bringing to our attention :) if you could please share this repo with other developers, it would be most appreciated!
